name: TownyAntiHome
version: ${project.version}
main: jirubizu.townyantihome.TownyAntiHome
api-version: 1.16
depend: [ Towny ]
authors: [ jirubizu ]
description: Prevent non-residents from setting home in towny claims
